import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Providers from "./providers";
import { ToastProvider } from "@/components/layout/ToastProvider";
import AuthBootstrap from "./AuthBootstrap";
import KakaoScript from "@/lib/utils/KakaoScript";
import { KakaoAddressScript } from "@/lib/utils/KakaoAddressScript";

const pretendard = localFont({
  src: [
    {
      path: "../assets/fonts/Pretendard-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pretendard-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pretendard-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../assets/fonts/Pretendard-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable} h-full`}>
      <body className="font-sans h-full overflow-hidden">
        <KakaoScript />
        <KakaoAddressScript />
        <AuthBootstrap />

        <div id="app-scroll-root" className="h-dvh overflow-y-scroll">
          <Providers>{children}</Providers>
          <ToastProvider />
        </div>
      </body>
    </html>
  );
}
